MVCApp/MVCApp/Controllers/DivesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    public class DivesController : Controller
    {
        private DiveModel db = new DiveModel();

        // GET: Dives
        public ActionResult Index()
        {
            var dives = db.Dives.Include(d => d.Competition1).Include(d => d.Competition2).Include(d => d.Competition3).Include(d => d.DiveChar51).Include(d => d.DiveChar52).Include(d => d.DiveChar53).Include(d => d.DiveCode11).Include(d => d.DiveCode12).Include(d => d.DiveCode13).Include(d => d.DiveCode21).Include(d => d.DiveCode22).Include(d => d.DiveCode23).Include(d => d.PlatformsHeight1).Include(d => d.PlatformsHeight2).Include(d => d.PlatformsHeight3);
            return View(dives.ToList());
        }

        // GET: Dives/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dive dive = db.Dives.Find(id);
            if (dive == null)
            {
                return HttpNotFound();
            }
            return View(dive);
        }
        

        

        // GET: Dives/Create
        public ActionResult Create()
        {
            ViewBag.Competition = new SelectList(db.Competitions, "CompetitionID", "Name");
            ViewBag.DiveChar5 = new SelectList(db.DiveChar5, "DiveCodeID", "BodyPosition");

          
            ViewBag.DiveCode1 = new SelectList(db.DiveCode1, "DiveCodeID", "DiveGroup");
            
            ViewBag.DiveCode2 = new SelectList(db.DiveCode2, "DiveCodeID", "DiveGroup");
           
            ViewBag.PlatformsHeight = new SelectList(db.PlatformsHeights, "PlatformsHeightID", "Height");
            return View();
        }

        // POST: Dives/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DiveID,Diver,Competition,DifficultyScore,DiveCode1,DiveCode2,DiveCode3,DiveCode4,DiveChar5,PlatformsHeight")] Dive dive)
        {
            if (ModelState.IsValid)
            {
                db.Dives.Add(dive);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            ViewBag.Competition = new SelectList(db.Competitions, "CompetitionID", "Name", dive.Competition);
            ViewBag.DiveChar5 = new SelectList(db.DiveChar5, "DiveCodeID", "BodyPosition", dive.DiveChar5);
            ViewBag.DiveCode1 = new SelectList(db.DiveCode1, "DiveCodeID", "DiveGroup", dive.DiveCode1);
            ViewBag.DiveCode2 = new SelectList(db.DiveCode2, "DiveCodeID", "DiveGroup", dive.DiveCode2);
            ViewBag.PlatformsHeight = new SelectList(db.PlatformsHeights, "PlatformsHeightID", "Height", dive.PlatformsHeight);
            return View(dive);
        }

        // GET: Dives/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dive dive = db.Dives.Find(id);
            if (dive == null)
            {
                return HttpNotFound();
            }
           
            ViewBag.Competition = new SelectList(db.Competitions, "CompetitionID", "Name", dive.Competition);
           
            ViewBag.DiveChar5 = new SelectList(db.DiveChar5, "DiveCodeID", "BodyPosition", dive.DiveChar5);
           
            ViewBag.DiveCode1 = new SelectList(db.DiveCode1, "DiveCodeID", "DiveGroup", dive.DiveCode1);
            
            ViewBag.DiveCode2 = new SelectList(db.DiveCode2, "DiveCodeID", "DiveGroup", dive.DiveCode2);
           
            ViewBag.PlatformsHeight = new SelectList(db.PlatformsHeights, "PlatformsHeightID", "Height", dive.PlatformsHeight);
            return View(dive);
        }

        // POST: Dives/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DiveID,Diver,Competition,DifficultyScore,DiveCode1,DiveCode2,DiveCode3,DiveCode4,DiveChar5,PlatformsHeight")] Dive dive)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dive).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            ViewBag.Competition = new SelectList(db.Competitions, "CompetitionID", "Name", dive.Competition);
            ViewBag.DiveChar5 = new SelectList(db.DiveChar5, "DiveCodeID", "BodyPosition", dive.DiveChar5);
            ViewBag.DiveCode1 = new SelectList(db.DiveCode1, "DiveCodeID", "DiveGroup", dive.DiveCode1);
            ViewBag.DiveCode2 = new SelectList(db.DiveCode2, "DiveCodeID", "DiveGroup", dive.DiveCode2);
           
           
            ViewBag.PlatformsHeight = new SelectList(db.PlatformsHeights, "PlatformsHeightID", "Height", dive.PlatformsHeight);
            return View(dive);
        }

        // GET: Dives/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dive dive = db.Dives.Find(id);
            if (dive == null)
            {
                return HttpNotFound();
            }
            return View(dive);
        }

        // POST: Dives/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dive dive = db.Dives.Find(id);
            db.Dives.Remove(dive);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCApp/MVCApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc; 
using MVCApp.Models; 

namespace MVCApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCApp/MVCApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCApp/MVCApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact us at Simhopp EU";
}

    <br /> <br /><br />
    <b> <div style="text-align:center"><h1>@ViewBag.Title!</h1></b>
    <h2></h2>
    <br /> <br />
           <address>
               <b>  Street: </b> Schillerstrasse 26
               <br />
               <b> City: </b>   Bruckmaier
               <br />
               <b> State/province/area:</b>  Freistaat Bayern
               <br />
               <b>Zip code  </b> 82515
               <br />
               <b>Country calling code</b>  +49
               <br />
               <b> Headquarters:</b> Germany
               <br />

               <b><abbr title="Phone number">Phone #:</abbr> </b> 08171 28 74 70
           </address>
        <div style="text-align:center">
            <address>
                <strong>Support:</strong>   <a href="mailto:SimhoppHelp@gmail.com">SimhoppHelp@gmail.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:SimhoppMoney@gmail.com">SimhoppMoney@gmail.com</a>
            </address>
        <br /> 
<br /> 

MVCApp/MVCApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<br />
<div style="text-align:center">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Simhopp EU</h1>
            <br />
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Competitions</h2>
            <p>
                View the current competitions, as well as where and where they will take place!
            </p>
            <br />
            <br />
            <p><a class="btn-lg btn-info" @Html.ActionLink("View the Competitions", "Index", "Competitions")</a></p>
        </div>

        <div class="col-md-4">
            <h2>Dives</h2>
            <p>Check out what dive your favorite diver strives to do. If you are a coach/diver then register a dive wish to  performe.</p>
            <br />
            <p><a class="btn-lg btn-info" @Html.ActionLink("View the Dives", "Index", "Dives") </a></p>
        </div>

        <div class="col-md-4">
            <h2>Contact</h2>
            <br />
            <p>Please contact us if you have any questions, whether personal or business-related.</p>
            <br />
            <p><a class="btn-lg btn-info" @Html.ActionLink("Contact Simhopp EU", "Contact", "Home")</a></p>
        </div>
    </div>
    <br <br />
    <br /><br /><br /><br /><br /><br /><br />